version: "3"
services:
  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    environment:
      - GRID_TIMEOUT=30000
      - GRID_BROWSER_TIMEOUT=30000

  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:latest
    shm_size: '512m'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  module1:
    image: cucumber/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=module1.xml
      - CUCUMBER_OPTIONS=classpath:features/module1
    volumes:
      - ./module1-result:/usr/share/selenium-docker/test-output
      - ./module1-result/json:/usr/share/selenium-docker/target/cucumber_json_reports

  module2:
    image: cucumber/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=module2.xml
      - CUCUMBER_OPTIONS=classpath:features/module2

    volumes:
      - ./module2-result:/usr/share/selenium-docker/test-output
      - ./module2-result/json:/usr/share/selenium-docker/target/cucumber_json_reports
